app = "wowlab-sentinel"
primary_region = "lhr"

[build]
  image = "ghcr.io/legacy3/wowlab-sentinel:latest"

[http_service]
  auto_start_machines = true
  auto_stop_machines = "off"
  force_https = true
  internal_port = 8080
  min_machines_running = 1

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  path = "/status"
  timeout = "5s"

[[metrics]]
  path = "/metrics"
  port = 8080

[[restart]]
  policy = "always"
  retries = 3

[[vm]]
  memory = "256mb"
  size = "shared-cpu-1x"
