[package]
name = "engine_new"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
bitflags = "2"
rhai = { version = "1", features = ["sync", "internals"] }

[dev-dependencies]
