app = "wowlab-server"
primary_region = "fra"

[build]
  image = "ghcr.io/legacy3/wowlab-server:latest"

[deploy]
  min_machines_running = 0

[restart]
  policy = "always"
  retries = 3

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = false

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
  auto_stop_machines = "off"
  auto_start_machines = false
